# Generated by Django 5.0.3 on 2024-03-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.BooleanField(default=False)),
                ('button', models.BooleanField(default=False)),
                ('robot_on', models.BooleanField(default=False)),
                ('reset_counter', models.BooleanField(default=False)),
                ('count_value', models.IntegerField(default=0)),
            ],
        ),
    ]
